Bugfix for undefined reference to '__atomic_load_8'
- Also for '__atomic_store_8' and __atomic_fetch_add_8'.
- When using std::atomic according to cppreference.com "On gcc and
  clang, some of the functionality described here requires linking
  against -latomic".
- Reproducible on debian buster on mips.